<a href="https://colab.research.google.com/github/antonum/sandbox/blob/big_query/bigquery_to_timescale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#it's better to match notebook location with CGP region
!curl ipinfo.io

{
  "ip": "35.237.107.22",
  "hostname": "22.107.237.35.bc.googleusercontent.com",
  "city": "North Charleston",
  "region": "South Carolina",
  "country": "US",
  "loc": "32.8546,-79.9748",
  "org": "AS396982 Google LLC",
  "postal": "29415",
  "timezone": "America/New_York",
  "readme": "https://ipinfo.io/missingauth"
}

In [3]:
#Connect notebook to your google cloud account
from google.colab import auth as google_auth
from google.cloud import aiplatform
from google.cloud import bigquery

#replace values below with your own Project and GCP Region
PROJECT_ID = "fhir-274320"
REGION = "us-central1"
google_auth.authenticate_user()
aiplatform.init(project=PROJECT_ID, location=REGION)

In [4]:
# Construct a BigQuery client object.
client = bigquery.Client(project=PROJECT_ID)

In [5]:


# TODO(developer): Set table_id to the ID of the table to read.
#table_id = 'your-project.your_dataset.your_table'  # Replace with your table ID
query = """
SELECT
*
FROM
  `bigquery-public-data.noaa_gsod.stations`
  --limit 10
"""

query_job = client.query(query)  # Use an f-string for clarity

results = query_job.result()  # Waits for the query to finish

#for row in results:
#  print(row)

To gather DDL for bigquery table use:
```
SELECT
 table_name, ddl
FROM
 bigquery-public-data.noaa_gsod.INFORMATION_SCHEMA.TABLES
 where table_name='stations';
```

BigQuery datatypes differ significantly from Postgres. You might need to adjust DDL.

In [6]:
import psycopg2
from google.colab import userdata
#CONNECTION="postgres://tsdbadmin:xxxxxxx@yyyyyyy.ocssgijfrc.tsdb.cloud.timescale.com:32753/tsdb?sslmode=require"
CONNECTION=userdata.get('TS_CONNECTION')
#CONNECTION=userdata.get('TS_CONNECTION_DEMO')
conn = psycopg2.connect(CONNECTION)
cursor = conn.cursor()

In [7]:
import pandas as pd
def sql_results_to_df(cursor):
  columns = [desc[0] for desc in cursor.description]
  data = cursor.fetchall()
  df = pd.DataFrame(data, columns=columns)
  return df

In [8]:
query = "CREATE SCHEMA IF NOT EXISTS weather;"
cursor.execute(query)
conn.commit()

In [9]:
query = "DROP TABLE IF EXISTS weather.stations;"
cursor.execute(query)
conn.commit()

In [10]:
#use for debugging if query fails
conn.commit()
cursor = conn.cursor()

In [11]:
query = """
CREATE TABLE weather.stations
(
  usaf char(10),
  wban char(10),
  name VARCHAR(100),
  country CHAR(2),
  state CHAR(8),
  call CHAR(8),
  lat FLOAT,
  lon FLOAT,
  elev FLOAT,
  begin CHAR(8),
  "end" CHAR(8)
);
"""
cursor.execute(query)
conn.commit()

In [12]:
# https://chatgpt.com/share/67a4f88c-bb48-8004-823a-a990e264658f (ChatGPT optimization)
from tqdm import tqdm
import psycopg2.extras

insert_query = """
INSERT INTO weather.stations (usaf, wban, name, country, state, call, lat, lon, elev, begin, "end")
VALUES %s
"""

batch_size = 20000  # Increased batch size
data_to_insert = []
n=0
cursor = conn.cursor()  # Create cursor once

for record in tqdm(results):
    data_to_insert.append(tuple(record))
    n=n+1
    if n % batch_size == 0:
        psycopg2.extras.execute_values(cursor, insert_query, data_to_insert)
        conn.commit()
        data_to_insert = []  # Clear buffer

# Insert any remaining records
if data_to_insert:
    psycopg2.extras.execute_values(cursor, insert_query, data_to_insert)
    conn.commit()

29590it [00:11, 2552.05it/s]

In [13]:
query = """
SELECT count(*)
FROM weather.stations;
"""
cursor.execute(query)
sql_results_to_df(cursor)

   count
0  29590

In [14]:
query = """
SELECT
 stn, date, temp, dewp, prcp
,fog,	rain_drizzle,	snow_ice_pellets,	hail,	thunder,	tornado_funnel_cloud
 --*
FROM
  `bigquery-public-data.noaa_gsod.gsod2024`
  --limit 10
--ORDER BY date
"""

query_job = client.query(query)
results = query_job.result()  # Waits for the query to finish

In [15]:
#df = pd.DataFrame(results.to_dataframe())
#df

In [16]:
query = "DROP TABLE IF EXISTS weather.observations;"
cursor.execute(query)
conn.commit()

In [17]:
# Cell to recreate the table
query = """
CREATE TABLE weather.observations
(
  stn char(10),
  date DATE,
  temp FLOAT,
  dewp FLOAT,
  prcp FLOAT,
  fog BOOLEAN,
  rain_drizzle BOOLEAN,
  snow_ice_pellets BOOLEAN,
  hail BOOLEAN,
  thunder BOOLEAN,
  tornado_funnel_cloud BOOLEAN
);
"""
cursor.execute(query)
conn.commit()

In [18]:
query = """
SELECT create_hypertable ('weather.observations', 'date',
      chunk_time_interval => interval '1month');
"""
cursor.execute(query)
conn.commit()

In [19]:

insert_query = """
INSERT INTO weather.observations (stn, date, temp, dewp, prcp, fog
, rain_drizzle,	snow_ice_pellets,	hail,	thunder,	tornado_funnel_cloud)
VALUES %s
"""

batch_size = 50000  # Increased batch size
data_to_insert = []
n=0
cursor = conn.cursor()  # Create cursor once

for record in tqdm(results):
    data_to_insert.append(tuple(record))
    n=n+1
    if n % batch_size == 0:
        psycopg2.extras.execute_values(cursor, insert_query, data_to_insert)
        conn.commit()
        data_to_insert = []  # Clear buffer

# Insert any remaining records
if data_to_insert:
    psycopg2.extras.execute_values(cursor, insert_query, data_to_insert)
    conn.commit()

3931419it [34:39, 1890.43it/s]

In [20]:
query = """
SELECT count(*)
FROM weather.observations;
"""
cursor.execute(query)
sql_results_to_df(cursor)

     count
0  3931419

In [21]:
query = """
ALTER TABLE weather.observations SET (timescaledb.compress = true);
"""
cursor.execute(query)
conn.commit()

In [22]:
query = """
SELECT add_compression_policy('weather.observations', compress_after => INTERVAL '1month');
"""
cursor.execute(query)
conn.commit()